# 1. Single Neuron From Scratch

A neuron is the building block of neural networks!
It takes inputs, multiplies by weights, adds bias, and applies an activation function.
Let's build one from scratch!


In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt


## 1. What is a Neuron?

A neuron takes inputs, multiplies by weights, adds a bias, and applies an activation function!
Output = activation(weight1 × input1 + weight2 × input2 + ... + bias)


In [ ]:
# Manual calculation: single neuron
# Inputs
inputs = torch.tensor([2.0, 3.0])

# Weights
weights = torch.tensor([0.5, 0.3])

# Bias
bias = 0.1

# Compute weighted sum
weighted_sum = weights[0] * inputs[0] + weights[1] * inputs[1] + bias

print("Single Neuron Calculation:")
print(f"Inputs: {inputs}")
print(f"Weights: {weights}")
print(f"Bias: {bias}")
print()
print(f"Weighted sum = {weights[0]} × {inputs[0]} + {weights[1]} × {inputs[1]} + {bias}")
print(f"Weighted sum = {weighted_sum:.2f}")
print()

# Apply activation (sigmoid)
activation = 1 / (1 + torch.exp(-weighted_sum))
print(f"After activation (sigmoid): {activation:.4f}")
print()
print("This is how a single neuron works!")


Single Neuron Calculation:
Inputs: tensor([2., 3.])
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Weighted sum = 0.5 × 2.0 + 0.30000001192092896 × 3.0 + 0.1
Weighted sum = 2.00

After activation (sigmoid): 0.8808

This is how a single neuron works!


## 2. Step 1: Initialize a Neuron

First, let's create a neuron class that can store weights and bias.
We'll build it step by step!


In [3]:
# Step 1: Create a simple neuron class that just stores weights and bias
class Neuron:
    """Single neuron from scratch - Step 1: Just initialization"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)

# Let's create a neuron and see what it looks like
neuron = Neuron(num_inputs=2)

print("Step 1: Neuron Initialization")
print(f"Number of inputs: 2")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print("Good! Our neuron now has weights and bias initialized.")


Step 1: Neuron Initialization
Number of inputs: 2
Weights: tensor([ 0.0166, -0.0366])
Bias: 0.0

Good! Our neuron now has weights and bias initialized.


## 3. Step 2: Calculate Weighted Sum

Now let's add a method to calculate the weighted sum (weights · inputs + bias).


In [4]:
# Step 2: Add method to calculate weighted sum
class Neuron:
    """Single neuron from scratch - Step 2: Add weighted sum calculation"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def weighted_sum(self, inputs):
        """Calculate: weights · inputs + bias"""
        return torch.dot(self.weights, inputs) + self.bias

# Test it
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])  # Set fixed weights for demo
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])
result = neuron.weighted_sum(inputs)

print("Step 2: Weighted Sum Calculation")
print(f"Inputs: {inputs}")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print(f"Weighted sum = weights · inputs + bias")
print(f"              = {neuron.weights} · {inputs} + {neuron.bias}")
print(f"              = {result:.4f}")
print()
print("Great! Now we can calculate the weighted sum.")


Step 2: Weighted Sum Calculation
Inputs: tensor([2., 3.])
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Weighted sum = weights · inputs + bias
              = tensor([0.5000, 0.3000]) · tensor([2., 3.]) + 0.1
              = 2.0000

Great! Now we can calculate the weighted sum.


## 4. Step 3: Add Activation Function

The activation function makes the neuron non-linear. Let's add sigmoid activation first.


In [5]:
# Step 3: Add sigmoid activation function
class Neuron:
    """Single neuron from scratch - Step 3: Add sigmoid activation"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def weighted_sum(self, inputs):
        """Calculate: weights · inputs + bias"""
        return torch.dot(self.weights, inputs) + self.bias
    
    def sigmoid(self, x):
        """Sigmoid activation: 1 / (1 + exp(-x))"""
        return 1 / (1 + torch.exp(-x))

# Test it step by step
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])  # Set fixed weights for demo
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])

# Step 1: Calculate weighted sum
ws = neuron.weighted_sum(inputs)
print("Step 3: Adding Activation Function")
print(f"1. Weighted sum = {ws:.4f}")

# Step 2: Apply sigmoid
output = neuron.sigmoid(ws)
print(f"2. After sigmoid activation = {output:.4f}")
print()
print("Perfect! Now we have a complete neuron with activation.")


Step 3: Adding Activation Function
1. Weighted sum = 2.0000
2. After sigmoid activation = 0.8808

Perfect! Now we have a complete neuron with activation.


## 5. Step 4: Complete Forward Pass

Now let's combine everything into a single `forward` method that does it all!

**What a neuron does:**
- Takes multiple inputs
- Multiplies by weights (importance of each input)
- Adds bias (shift the output)
- Applies activation function (non-linearity)

**Key components:**
- **Weights**: How important each input is
- **Bias**: Shifts the weighted sum
- **Activation**: Makes neuron non-linear (sigmoid, ReLU, tanh, etc.)

**Forward pass:**
1. Weighted sum = weights · inputs + bias
2. Output = activation(weighted sum)

**Remember:** A single neuron is the building block of neural networks!


In [6]:
# Step 4: Complete neuron with forward pass
class Neuron:
    """Single neuron from scratch - Complete version"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def sigmoid(self, x):
        """Sigmoid activation: 1 / (1 + exp(-x))"""
        return 1 / (1 + torch.exp(-x))
    
    def forward(self, inputs):
        """Forward pass: weighted sum + activation"""
        # Step 1: Calculate weighted sum
        weighted_sum = torch.dot(self.weights, inputs) + self.bias
        # Step 2: Apply activation
        output = self.sigmoid(weighted_sum)
        return output

# Test the complete neuron
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])  # Set fixed weights for demo
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])
output = neuron.forward(inputs)

print("Step 4: Complete Forward Pass")
print(f"Inputs: {inputs}")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print(f"Output: {output:.4f}")
print()
print("Excellent! Our neuron is complete and working!")


Step 4: Complete Forward Pass
Inputs: tensor([2., 3.])
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Output: 0.8808

Excellent! Our neuron is complete and working!


## 6. Test with Different Inputs

Let's see how our neuron responds to different inputs!


In [7]:
# Test neuron with different inputs
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])
neuron.bias = 0.1

test_inputs = [
    torch.tensor([0.0, 0.0]),
    torch.tensor([1.0, 0.0]),
    torch.tensor([0.0, 1.0]),
    torch.tensor([1.0, 1.0]),
    torch.tensor([2.0, 3.0]),
]

print("Testing neuron with different inputs:")
print(f"Weights: {neuron.weights}, Bias: {neuron.bias}")
print()
print("Input          | Weighted Sum | Output (sigmoid)")
print("-" * 50)

for inp in test_inputs:
    weighted_sum = torch.dot(neuron.weights, inp) + neuron.bias
    output = neuron.forward(inp)
    print(f"{str(inp):14} | {weighted_sum:11.4f} | {output:14.4f}")


Testing neuron with different inputs:
Weights: tensor([0.5000, 0.3000]), Bias: 0.1

Input          | Weighted Sum | Output (sigmoid)
--------------------------------------------------
tensor([0., 0.]) |      0.1000 |         0.5250
tensor([1., 0.]) |      0.6000 |         0.6457
tensor([0., 1.]) |      0.4000 |         0.5987
tensor([1., 1.]) |      0.9000 |         0.7109
tensor([2., 3.]) |      2.0000 |         0.8808


## 8. Try Different Activation Functions

Neurons can use different activation functions! Let's add support for more activations.


In [9]:
# Enhanced neuron with multiple activation functions
class Neuron:
    """Single neuron with multiple activation functions"""
    
    def __init__(self, num_inputs, activation='sigmoid'):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
        self.activation_name = activation
    
    def activate(self, x):
        """Apply activation function"""
        if self.activation_name == 'sigmoid':
            return 1 / (1 + torch.exp(-x))
        elif self.activation_name == 'relu':
            return torch.maximum(torch.tensor(0.0), x)
        elif self.activation_name == 'tanh':
            return torch.tanh(x)
        else:
            return x  # No activation (linear)
    
    def forward(self, inputs):
        """Forward pass: weighted sum + activation"""
        weighted_sum = torch.dot(self.weights, inputs) + self.bias
        output = self.activate(weighted_sum)
        return output

# Test different activation functions
print("Testing different activation functions:")
print("Input = 2.0, Weights = [1.0], Bias = 0.0")
print()

activations = ['sigmoid', 'relu', 'tanh', 'linear']

for act_name in activations:
    neuron = Neuron(num_inputs=1, activation=act_name)
    neuron.weights = torch.tensor([1.0])
    neuron.bias = 0.0
    
    input_val = torch.tensor([2.0])
    weighted_sum = torch.dot(neuron.weights, input_val) + neuron.bias
    output = neuron.forward(input_val)
    
    print(f"{act_name:8s}: weighted_sum = {weighted_sum:.2f} → output = {output:.4f}")


Testing different activation functions:
Input = 2.0, Weights = [1.0], Bias = 0.0

sigmoid : weighted_sum = 2.00 → output = 0.8808
relu    : weighted_sum = 2.00 → output = 2.0000
tanh    : weighted_sum = 2.00 → output = 0.9640
linear  : weighted_sum = 2.00 → output = 2.0000


## 10. Key Takeaways

**What a neuron does:**
- Takes multiple inputs
- Multiplies by weights (importance of each input)
- Adds bias (shift the output)
- Applies activation function (non-linearity)

**Key components:**
- **Weights**: How important each input is
- **Bias**: Shifts the weighted sum
- **Activation**: Makes neuron non-linear (sigmoid, ReLU, tanh, etc.)

**Forward pass:**
1. Weighted sum = weights · inputs + bias
2. Output = activation(weighted sum)

**Remember:** A single neuron is the building block of neural networks!
